create table if not exists users
(
    user_id    integer generated by default as identity
        constraint users_pk
            primary key,
    user_name  varchar(255) not null,
    user_email varchar(255) not null
        constraint users_pk2
            unique
);

create table if not exists items
(
    item_id          integer generated always as identity
        constraint items_pk
            primary key,
    item_name        varchar(255) not null,
    item_description varchar(200) not null,
    item_ownerid     integer      not null,
    item_available   boolean      not null
);

